/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MainImport } from './routes/_main'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as MainIndexImport } from './routes/_main/index'
import { Route as AdminDashboardImport } from './routes/admin/dashboard'
import { Route as MainRecommendationNumberImport } from './routes/_main/recommendation/$number'

// Create/Update Routes

const MainRoute = MainImport.update({
  id: '/_main',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  path: '/admin/',
  getParentRoute: () => rootRoute,
} as any)

const MainIndexRoute = MainIndexImport.update({
  path: '/',
  getParentRoute: () => MainRoute,
} as any)

const AdminDashboardRoute = AdminDashboardImport.update({
  path: '/admin/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const MainRecommendationNumberRoute = MainRecommendationNumberImport.update({
  path: '/recommendation/$number',
  getParentRoute: () => MainRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainImport
      parentRoute: typeof rootRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardImport
      parentRoute: typeof rootRoute
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexImport
      parentRoute: typeof MainImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof rootRoute
    }
    '/_main/recommendation/$number': {
      id: '/_main/recommendation/$number'
      path: '/recommendation/$number'
      fullPath: '/recommendation/$number'
      preLoaderRoute: typeof MainRecommendationNumberImport
      parentRoute: typeof MainImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  MainRoute: MainRoute.addChildren({
    MainIndexRoute,
    MainRecommendationNumberRoute,
  }),
  AdminDashboardRoute,
  AdminIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_main",
        "/admin/dashboard",
        "/admin/"
      ]
    },
    "/_main": {
      "filePath": "_main.tsx",
      "children": [
        "/_main/",
        "/_main/recommendation/$number"
      ]
    },
    "/admin/dashboard": {
      "filePath": "admin/dashboard.tsx"
    },
    "/_main/": {
      "filePath": "_main/index.tsx",
      "parent": "/_main"
    },
    "/admin/": {
      "filePath": "admin/index.tsx"
    },
    "/_main/recommendation/$number": {
      "filePath": "_main/recommendation/$number.tsx",
      "parent": "/_main"
    }
  }
}
ROUTE_MANIFEST_END */
