/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as mainImport } from './routes/__main'
import { Route as mainIndexImport } from './routes/__main/index'

// Create/Update Routes

const mainRoute = mainImport.update({
  id: '/__main',
  getParentRoute: () => rootRoute,
} as any)

const mainIndexRoute = mainIndexImport.update({
  path: '/',
  getParentRoute: () => mainRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__main': {
      id: '/__main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainImport
      parentRoute: typeof rootRoute
    }
    '/__main/': {
      id: '/__main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainIndexImport
      parentRoute: typeof mainImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  mainRoute: mainRoute.addChildren({ mainIndexRoute }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/__main"
      ]
    },
    "/__main": {
      "filePath": "__main.tsx",
      "children": [
        "/__main/"
      ]
    },
    "/__main/": {
      "filePath": "__main/index.tsx",
      "parent": "/__main"
    }
  }
}
ROUTE_MANIFEST_END */
